services:

  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3307
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: onlineshop1
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./mysql_home:/var/lib/mysql
      - ./initDB.sql:/docker-entrypoint-initdb.d/initDB.sql  
  keycloak-service:
    image: quay.io/keycloak/keycloak:18.0.2
    restart: always
    container_name: keycloak-service
    hostname: keycloak-service
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8181:8181
    expose:
      - 8181
    command: ["start-dev", "--http-port=8181"]

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rmq3"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "123456"
    ports:
      - "5672:5672"
      - "15672:15672"
